os:
  linux:
    style:
      background: { Fixed: 33 }
      foreground: White
    icon: "\uf17c" # nf-fa-linux
  mac:
    style:
      background: { Fixed: 33 }
      foreground: White
    icon: "\uf179" # nf-fa-apple
  windows:
    style:
      background: { Fixed: 33 }
      foreground: White
    icon: "\uf17a" # nf-fa-windows

shell:
  bash:
    style:
      background: White
      foreground: Green
    icon: "Bash"

  zsh:
    style:
      background: White
      foreground: Green
    icon: "Zsh"

  fish:
    style:
      background: White
      foreground: Green
    icon: "\uf739" # nf-mdi-fish

user:
  style:
    background: { Fixed: 8 }
    foreground: White
  display_host: true

directory:
  home: "~"
  normal:
    style:
      background: Blue
      foreground: Black
  error:
    style:
      background: Red
      foreground: Black
  shrink:
    enabled: true
    max_len: 1

git_repo:
  icons:
    branch: "\uf418" # nf-oct-git_branch
    tag: "\uf412" # nf-oct-tag
    commit: "\uf417" # nf-oct-git_commit
    modified: "…"
    added: "+"
    deleted: "-"
    added_deleted: "±"
    conflicted: "\uf47f" # nf-oct-git_compare
    behind: "\uf175" # nf-fa-long_arrow_down
    ahead: "\uf176" # nf-fa-long_arrow_up

  clean:
    style:
      background: Green
      foreground: Black

  unstaged:
    style:
      background: Yellow
      foreground: Black

  staged:
    style:
      background: Green
      foreground: Black

  conflicted:
    style:
      background: Red
      foreground: Black

  display_master: true
  display_tag: true
  commit_hash_len: 6

git_user:
  style:
    background: { Fixed: 117 }
    foreground: Black
  icon: "\uf2c0" # nf-fa-user_o

status:
  icons:
    succeeded: "✓"
    failed: "\uf06a" # nf-fa-exclamation_circle
    root: "\ue00a" # nf-pom-external_interruption
    jobs: "\uf013" # nf-fa-gear

  succeeded:
    style:
      background: White
      foreground: Blue

  failed:
    style:
      background: Red
      foreground: White
    display_exit_status: true

time:
  style:
    background: { Fixed: 8 }
    foreground: White
  format: "\uf017 %Y/%m/%d %H:%M:%S" # See https://docs.rs/chrono/0.3.0/chrono/format/strftime/
  utc: false

duration:
  style:
    background: { Fixed: 242 }
    foreground: White
  icon: "\ufa1a" # nf-mdi-timer

venv:
  style:
    background: Black
    foreground: White
  icon: "\uf81f" # nf-mdi-language_python

segment_separators:
  left_solid: "\ue0b0" # nf-pl-left_hard_divider
  left_wire: "\ue0b1" # nf-pl-left_soft_divider

segments:
  - - os
    - user
    - directory
    - git_repo
    - git_user
    - venv
  - - duration
    - status
